users :
  type: rest
  resource:     "TeckboardCoreBundle:Users"
  name_prefix:  api_user_

organizations :
  type: rest
  resource:     "TeckboardCoreBundle:Organizations"
  name_prefix:  api_organization_

boards :
  type: rest
  resource:     "TeckboardCoreBundle:Boards"
  name_prefix:  api_board_

widgets :
  type: rest
  resource:     "TeckboardCoreBundle:Widgets"
  name_prefix:  api_widget_